<a href="https://colab.research.google.com/github/GeremiccaAndrea/Python/blob/main/Copia_di_Pandas_e_drive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pandas

Per caricare i dati da un file in un databframe con Pandas è necessario prima caricare nel proprio Drive i file che si intendono utilizzare.

Poi bisogna far sì che il notebook di COlab abbia accesso al Drive tramite il metodo mount() di drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd #importa la libreria pandas

A questo punto basta utilizzare il metodo read_csv() (o altro a seconda del file) per leggere il file:

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/winemag-data-130k-v2.csv', index_col=0)
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [ ]:
pd.DataFrame({'Hobby': ['Calcio', 'VideoGame'], 
              'Materie preferite': ['Informatica', 'Educazione fisica']},
             index=['Product A', 'Product B'])

               Hobby  Materie preferite
Product A     Calcio        Informatica
Product B  VideoGame  Educazione fisica

Si vogliono memorizzare i voti di alcuni studenti in alcune materie. 
lo studente Neri ha preso 4 in informatica, 5 in sistemi e 2 in tecnologie.
lo studente Bernasconi ha preso 6 in informatica, 2 in sistemi e 8 in tecnologie.
Caricare i dati in un DataFrame chiamato Voti

In [ ]:
Voti = pd.DataFrame({'Informatica': [4,6], 
              'Sistemi': [5,2],
              'Tecnologie': [2,8]},
             index=["Neri", "Bernasconi"])
print(Voti)

            Informatica  Sistemi  Tecnologie
Neri                  4        5           2
Bernasconi            6        2           8

In [ ]:
#stampa le prime e le ultime 5 
df.country
#oppure 
df['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [ ]:
#per visualizzare il primo 
df['country'][0]

'Italy'

In [ ]:
df.iloc[0] # mostra tutte le informazioni della colonna 0

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [ ]:
df.iloc[0:3] # mostra tutte le informazioni della colonna dalla 0 alla 3

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

In [ ]:
df.iloc[:, 0:2] # :, 0 mostra tutti gli elementi 0:2 invece mostra le colonne in quel range

         country                                        description
0          Italy  Aromas include tropical fruit, broom, brimston...
1       Portugal  This is ripe and fruity, a wine that is smooth...
2             US  Tart and snappy, the flavors of lime flesh and...
3             US  Pineapple rind, lemon pith and orange blossom ...
4             US  Much like the regular bottling from 2012, this...
...          ...                                                ...
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...
129967        US  Citation is given as much as a decade of bottl...
129968    France  Well-drained gravel soil gives this wine its c...
129969    France  A dry style of Pinot Gris, this is crisp with ...
129970    France  Big, rich and off-dry, this is powered by inte...

[129971 rows x 2 columns]

In [ ]:
df.tail() #mostra gli ultimi 5

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
df.country == 'Italy' #controlla se nella colonna country è presente italy

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [ ]:
df[df.country == 'US'] #visualizza tutti i vini americani

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129945,US,Hailing from one of the more popular vineyards...,Jurassic Park Vineyard Old Vines,90,20.0,California,Santa Ynez Valley,Central Coast,Matt Kettmann,@mattkettmann,Birichino 2013 Jurassic Park Vineyard Old Vine...,Chenin Blanc,Birichino
129949,US,There's no bones about the use of oak in this ...,Barrel Fermented,90,35.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Flora Springs 2013 Barrel Fermented Chardonnay...,Chardonnay,Flora Springs
129950,US,This opens with herbaceous dollops of thyme an...,Blocks 7 & 22,90,35.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Hendry 2012 Blocks 7 & 22 Zinfandel (Napa Valley),Zinfandel,Hendry
129952,US,This Zinfandel from the eastern section of Nap...,NaN,90,22.0,California,Chiles Valley,Napa,Virginie Boone,@vboone,Houdini 2011 Zinfandel (Chiles Valley),Zinfandel,Houdini
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation

In [ ]:
#trova tutti i vini italiani che costano più di 200 euro 
df[(df['country'] == 'Italy') & (df['price'] > 200)] # in pandas and = &

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1563,Italy,Recently implemented winemaker and cellar chan...,Sassicaia,97,220.0,Tuscany,Bolgheri Sassicaia,NaN,NaN,NaN,Tenuta San Guido 2008 Sassicaia (Bolgheri Sas...,Red Blend,Tenuta San Guido
1564,Italy,The 2008 Ornellaia delivers concentrated aroma...,Ornellaia,97,215.0,Tuscany,Bolgheri Superiore,NaN,NaN,NaN,Tenuta dell'Ornellaia 2008 Ornellaia (Bolgher...,Red Blend,Tenuta dell'Ornellaia
3201,Italy,"Cassis, bell pepper, toast, French oak and coc...",Redigaffi,90,400.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Tua Rita 2013 Redigaffi Merlot (Toscana),Merlot,Tua Rita
4522,Italy,Roberto Conterno didn't make his flagship Monf...,Francia,95,225.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Giacomo Conterno 2011 Francia (Barolo),Nebbiolo,Giacomo Conterno
5511,Italy,Bright cherry and blue floral aromas come with...,NaN,93,209.0,Tuscany,Brunello di Montalcino,NaN,Kerin O’Keefe,@kerinokeefe,Salvioni 2008 Brunello di Montalcino,Sangiovese,Salvioni
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121453,Italy,"Underbrush, sunbaked soil, toast, and espresso...",Lazzarito,90,210.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Vietti 2012 Lazzarito (Barolo),Nebbiolo,Vietti
125833,Italy,There's always something magical about Gaja's ...,Sorì San Lorenzo,96,495.0,Piedmont,Langhe,NaN,NaN,NaN,Gaja 2009 Sorì San Lorenzo Nebbiolo (Langhe),Nebbiolo,Gaja
125846,Italy,A tiny percentage of Barbera grapes accounts f...,Conteisa,95,240.0,Piedmont,Langhe,NaN,NaN,NaN,Gaja 2008 Conteisa Nebbiolo (Langhe),Nebbiolo,Gaja
125847,Italy,Costa Russi presents a dark wall of ripe fruit...,Costa Russi,95,495.0,Piedmont,Langhe,NaN,NaN,NaN,Gaja 2009 Costa Russi Nebbiolo (Langhe),Nebbiolo,Gaja
127433,Italy,Gaja's latest Barbaresco shows deep aromatic l...,NaN,93,255.0,Piedmont,Barbaresco,NaN,NaN,NaN,Gaja 2009 Barbaresco,Nebbiolo,Gaja

In [ ]:
#trovare i vini italiani e francesi 
df[(df['country'] == 'Italy') | (df['country'] == 'France')] # in pandas or si fa |

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
#trova i vini francesi,italiani e statunitensi
df[df['country'].isin(['Italy', 'France', 'US'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
df.loc[df['price'].notnull()] #stampa i vini dove abbiamo il prezzo

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
df.loc[df['price'].isnull()] #stampa i vini dove non abbiamo il prezzo

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
30,France,Red cherry fruit comes laced with light tannin...,Nouveau,86,NaN,Beaujolais,Beaujolais-Villages,NaN,Roger Voss,@vossroger,Domaine de la Madone 2012 Nouveau (Beaujolais...,Gamay,Domaine de la Madone
31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2010 Calanìca Nero d'Avola-...,Red Blend,Duca di Salaparuta
32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2011 Calanìca Grillo-Viogni...,White Blend,Duca di Salaparuta
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129844,Italy,"Doga delle Clavule is a neutral, mineral-drive...",Doga delle Clavule,86,NaN,Tuscany,Morellino di Scansano,NaN,NaN,NaN,Caparzo 2006 Doga delle Clavule (Morellino di...,Sangiovese,Caparzo
129860,Portugal,This rich wine has a firm structure as well as...,Pacheca Superior,90,NaN,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta da Pacheca 2013 Pacheca Superior Red (D...,Portuguese Red,Quinta da Pacheca
129863,Portugal,This mature wine that has 50% Touriga Nacional...,Reserva,90,NaN,Dão,NaN,NaN,Roger Voss,@vossroger,Seacampo 2011 Reserva Red (Dão),Portuguese Red,Seacampo
129893,Italy,"Aromas of passion fruit, hay and a vegetal not...",Corte Menini,91,NaN,Veneto,Soave Classico,NaN,Kerin O’Keefe,@kerinokeefe,Le Mandolare 2015 Corte Menini (Soave Classico),Garganega,Le Mandolare
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart

In [ ]:
#visualizzare tutti i prezzi dei vini 
df['price']

0          NaN
1         15.0
2         14.0
3         13.0
4         65.0
          ...
129966    28.0
129967    75.0
129968    30.0
129969    32.0
129970    21.0
Name: price, Length: 129971, dtype: float64

In [ ]:
#trovare il prezzo minimo 
min(df['price'])
#oppure 
df['price'].min() #quello più corretto

4.0

In [ ]:
#trova quello con il prezzo più alto 
df['price'].max()

3300.0

In [ ]:
#trovare il nome del vino che costa di più 
df[df['price']== df['price'].max()]['title']

80290    Château les Ormes Sorbet 2013  Médoc
Name: title, dtype: object

In [ ]:
#trovare il nome del vino che costa di meno , il suo prezzo e i suoi punti 
df[df['price']== df['price'].min()][['title', 'price', 'points']]

                                                    title  price  points
1987    Felix Solis 2013 Flirty Bird Syrah (Vino de la...    4.0      85
20484              Dancing Coyote 2015 White (Clarksburg)    4.0      85
29553           Broke Ass 2009 Red Malbec-Syrah (Mendoza)    4.0      84
31530                   Bandit NV Chardonnay (California)    4.0      84
59507     Pam's Cuties NV Unoaked Chardonnay (California)    4.0      83
61768            Terrenal 2010 Cabernet Sauvignon (Yecla)    4.0      84
64590                       Bandit NV Merlot (California)    4.0      86
110255                      Bandit NV Merlot (California)    4.0      84
112919   Terrenal 2010 Estate Bottled Tempranillo (Yecla)    4.0      84
117303  Felix Solis 2012 Flirty Bird White (Vino de la...    4.0      82
126096  Cramele Recas 2011 UnWineD Pinot Grigio (Viile...    4.0      86

In [ ]:
#somma di tutti punti di tutti i vini 
df['points'].sum()

11495563

In [ ]:
#trovare il prezzo medio dei vini 
df['price'].mean()

35.363389129985535

In [ ]:
#nomi della casa prodruttrice e del vino che costano più della media 
df[df['price'] > df['price'].mean()][['winery', 'title']]

                     winery                                              title
4              Sweet Cheeks  Sweet Cheeks 2012 Vintner's Reserve Wild Child...
25      Castello di Amorosa  Castello di Amorosa 2011 King Ridge Vineyard P...
33                  Envolve  Envolve 2010 Puma Springs Vineyard Red (Dry Cr...
35                    Erath         Erath 2010 Hyland Pinot Noir (McMinnville)
45                   Tarara           Tarara 2010 #SocialSecret Red (Virginia)
...                     ...                                                ...
129955            Dog Point            Dog Point 2012 Chardonnay (Marlborough)
129959    Cave de Turckheim  Cave de Turckheim 2010 Brand Grand Cru Pinot G...
129960  Caves Transmontanas  Caves Transmontanas 2006 Vértice Pinot Noir (D...
129962             Cusumano  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...
129967             Citation                  Citation 2004 Pinot Noir (Oregon)

[39743 rows x 2 columns]

In [ ]:
#trovare il numero dei vini americani 
len(df[df['country'] == 'US'])
#oppure 
df[df['country'] == 'US']['country'].count()

54504